SET timezone = 'Asia/Ho_Chi_Minh';

CREATE TABLE FETCH_LOGS (
    ID SERIAL PRIMARY KEY,
    URL VARCHAR(100) NOT NULL,
    FETCHED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE NEWS (
    ID SERIAL PRIMARY KEY,
    NEWS_SOURCE_ID INT NOT NULL,
    TITLE VARCHAR(250),
    URL VARCHAR(250),
    IMAGE VARCHAR(250),
    CONTENT VARCHAR(250),
    DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);