CREATE TABLE NEWS (
    ID SERIAL PRIMARY KEY,
    NEWS_SOURCE_ID INT NOT NULL,
    TITLE VARCHAR,
    URL VARCHAR,
    IMAGE VARCHAR,
    CONTENT VARCHAR,
    DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);