CREATE TABLE FETCH_LOGS (
    ID SERIAL PRIMARY KEY,
    URL VARCHAR(100) NOT NULL,
    FETCHED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE NEWS (
    ID SERIAL PRIMARY KEY,
    NEWS_SOURCE_ID INT NOT NULL,
    TITLE VARCHAR,
    URL VARCHAR,
    IMAGE VARCHAR,
    CONTENT VARCHAR,
    DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);