SET timezone = 'Asia/Ho_Chi_Minh';

CREATE TABLE CATEGORY (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(250),
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE NEWS_SOURCES (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(250),
    LINK VARCHAR(100) NOT NULL,
    HEADERS TEXT,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE NEW_SOURCES_SELECTORS (
    ID SERIAL PRIMARY KEY,
    NEWS_SOURCE_ID INTEGER NOT NULL REFERENCES NEWS_SOURCES(ID),
    TITLE_SELECTOR TEXT NOT NULL,
    IMAGE_SELECTOR TEXT NOT NULL,
    POST_LINK_SELECTOR TEXT NOT NULL,
    CONTENT_SELECTOR TEXT NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE TASKS (
    ID SERIAL PRIMARY KEY,
    CODE VARCHAR(100) UNIQUE, 
    NAME VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(250),
    CATEGORY_ID INTEGER NOT NULL REFERENCES CATEGORY(ID),
    NEWS_SOURCE_ID INTEGER NOT NULL REFERENCES NEWS_SOURCES(ID),
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE TASK_CONFIGS (
    ID SERIAL PRIMARY KEY,
    TASK_ID VARCHAR(100) NOT NULL UNIQUE REFERENCES TASKS(CODE),
    IS_ENABLED BOOLEAN NOT NULL DEFAULT FALSE,
    RUN_AT INTEGER NOT NULL DEFAULT 0,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE TASK_LOGS (
    ID SERIAL PRIMARY KEY,
    TASK_ID VARCHAR(100) NOT NULL REFERENCES TASKS(CODE),
    STATUS VARCHAR(50) NOT NULL,
    DESCRIPTION TEXT DEFAULT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
