CREATE TABLE IF NOT EXISTS CATEGORY (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(250),
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS NEWS_SOURCES (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(250),
    LINK VARCHAR(100) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS TASKS (
    ID SERIAL PRIMARY KEY,
    CODE VARCHAR(100) UNIQUE, 
    NAME VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(250),
    CATEGORY_ID INTEGER NOT NULL REFERENCES CATEGORY(ID),
    NEWS_SOURCE_ID INTEGER NOT NULL REFERENCES NEWS_SOURCES(ID)
);

CREATE TABLE IF NOT EXISTS TASK_LOGS (
    ID SERIAL PRIMARY KEY,
    TASK_ID VARCHAR(100) NOT NULL REFERENCES TASKS(CODE),
    STATUS VARCHAR(50) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
