CREATE TABLE TASKS (
    ID SERIAL PRIMARY KEY,
    CODE VARCHAR(100) UNIQUE, 
    NAME VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(250),
    CATEGORY_ID INTEGER NOT NULL REFERENCES CATEGORY(ID),
    NEWS_SOURCE_ID INTEGER NOT NULL REFERENCES NEWS_SOURCES(ID),
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE TASK_CONFIGS (
    ID SERIAL PRIMARY KEY,
    TASK_ID VARCHAR(100) NOT NULL UNIQUE REFERENCES TASKS(CODE),
    IS_ENABLED BOOLEAN NOT NULL DEFAULT FALSE,
    RUN_AT INTEGER NOT NULL DEFAULT 0,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE TASK_LOGS (
    ID SERIAL PRIMARY KEY,
    TASK_ID VARCHAR(100) NOT NULL REFERENCES TASKS(CODE),
    STATUS VARCHAR(50) NOT NULL,
    DESCRIPTION TEXT DEFAULT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
