CREATE TABLE CATEGORY (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(250),
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE NEWS_SOURCES (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(250),
    LINK VARCHAR(100) NOT NULL,
    HEADERS TEXT,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE NEW_SOURCES_SELECTORS (
    ID SERIAL PRIMARY KEY,
    NEWS_SOURCE_ID INTEGER NOT NULL REFERENCES NEWS_SOURCES(ID),
    ITEMS_SELECTOR TEXT NOT NULL,
    TITLE_SELECTOR TEXT NOT NULL,
    IMAGE_SELECTOR TEXT NOT NULL,
    POST_LINK_SELECTOR TEXT NOT NULL,
    CONTENT_SELECTOR TEXT NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);